export const PORTFOLIO_DATA = {
  name: "Ofentse Esrom Moshwaneng",
  title: "Computer Science Graduate",
  description: "seeking opportunities in technology and digital innovation",
  location: "Pretoria, South Africa",
  address: "291 General Bayers Street, Pretoria",
  addressMapUrl: "https://maps.google.com/maps?q=291+General+Bayers+Street+Pretoria&t=&z=16&ie=UTF8&iwloc=&output=embed",
  email: "djmsima@outlook.com",
  phone: "071 297 7758",
  birthdate: "29 October 2003",
  driverLicense: "Code 10",
  social: {
    github: "https://github.com/Gorillmac",
    instagram: "https://instagram.com/msima_ofentse",
    whatsapp: "https://wa.me/27712977758",
  },
  resumeLink: "/Ofentse_Moshwaneng_CV.html",
  skills: {
    technical: [
      { name: "HTML5 & CSS3", percentage: 85 },
      { name: "JavaScript", percentage: 80 },
      { name: "Node.js", percentage: 75 },
      { name: "TypeScript", percentage: 75 },
      { name: "React JS", percentage: 75 },
      { name: "Java & Kotlin", percentage: 80 },
      { name: "Python", percentage: 75 },
      { name: "MySQL & Postgres", percentage: 80 },
      { name: "PHP", percentage: 75 },
    ],
    professional: [
      { name: "Problem Solving", percentage: 85 },
      { name: "Team Collaboration", percentage: 90 },
      { name: "Adaptability", percentage: 85 },
      { name: "Communication", percentage: 80 },
    ],
  },
  projects: [
    {
      id: 1,
      title: "Loan Management System",
      description: "A comprehensive web platform enabling users to apply for personal loans without background checks. As the primary developer, I implemented a secure authentication system, designed the database schema for storing loan applications, and created an intuitive dashboard for users to monitor loan status. The system includes automated email notifications and payment calculation functionality.",
      detailedRole: "Led the full-stack development from concept to deployment. Designed the database schema, implemented secure user authentication, and built an admin panel for loan approval processing. Overcame challenges in implementing secure financial transactions and user verification.",
      keyFeatures: ["Secure user authentication", "Loan application workflow", "Real-time status updates", "Admin approval dashboard", "Automated email notifications"],
      image: "https://images.unsplash.com/photo-1579621970588-a35d0e7ab9b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
      tags: ["PHP", "Hack", "CSS", "Web Development", "MySQL"],
      demoLink: "https://github.com/Gorillmac",
      codeLink: "https://github.com/Gorillmac",
    },
    {
      id: 2,
      title: "Agile Poker Planning Tool",
      description: "A collaborative web application that enables Agile development teams to efficiently estimate task complexity using the Planning Poker technique. The tool features real-time voting, result visualization, and integration with popular project management platforms.",
      detailedRole: "Served as frontend developer in a team of four. Designed and implemented the user interface using React and TypeScript. Integrated with WebSocket for real-time voting functionality. Created responsive design with accessibility features and implemented data visualization components.",
      keyFeatures: ["Real-time collaborative estimation", "Story point voting system", "Interactive results dashboard", "Team member management", "Session history tracking"],
      image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
      tags: ["React JS", "TypeScript", "Frontend Development", "Agile", "WebSockets"],
      demoLink: "https://github.com/Gorillmac",
      codeLink: "https://github.com/Gorillmac",
    },
    {
      id: 3,
      title: "QuickHireHub",
      description: "An enterprise-grade job recruitment platform that connects employers with qualified candidates. The system features comprehensive profile creation, automated matching algorithms, interview scheduling, and applicant tracking functionality.",
      detailedRole: "Implemented the core backend functionality using Java and integrated with a lightweight frontend. Designed database structures for storing user profiles, job listings, and application status. Created a matching algorithm to recommend suitable candidates to employers based on skill requirements.",
      keyFeatures: ["Advanced job search filters", "Candidate-employer matching", "Application tracking system", "Resume parsing", "Interview scheduling"],
      image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
      tags: ["Java", "HTML", "JavaScript", "CSS", "SQL"],
      demoLink: "https://github.com/Gorillmac",
      codeLink: "https://github.com/Gorillmac",
    },
    {
      id: 4,
      title: "Personal Portfolio Website",
      description: "A modern, interactive personal portfolio website showcasing my professional skills, projects, and experiences. The site features responsive design, smooth animations, and an integrated contact system.",
      detailedRole: "Designed and implemented the entire website from wireframes to deployment. Used React with TypeScript for component development, Tailwind CSS for styling, and Framer Motion for advanced animations. Implemented responsive design to ensure optimal viewing across all devices.",
      keyFeatures: ["Interactive UI with animations", "Responsive design", "Project showcase with filtering", "Contact form with validation", "Performance optimization"],
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=500",
      tags: ["React", "Tailwind CSS", "JavaScript", "Framer Motion", "Responsive Design"],
      demoLink: "https://github.com/Gorillmac",
      codeLink: "https://github.com/Gorillmac",
    },
  ],
  education: {
    degree: "Diploma in Computer Science",
    institution: "Tshwane University of Technology",
    period: "Expected Completion: June 2025",
    details: "Pre-WIL confirmation letter available"
  },
  experience: {
    title: "Stock Counter (Part-Time)",
    company: "CountIT",
    location: "Pretoria, South Africa",
    period: "February 2023 - Present (as needed)",
    description: "Working on-demand as a skilled inventory specialist, conducting systematic counts at retail and warehouse facilities throughout Pretoria. This role has strengthened my attention to detail, data verification skills, and ability to work efficiently under time constraints.",
    responsibilities: [
      "Conduct comprehensive inventory audits at various retail and warehouse locations throughout Pretoria",
      "Maintain precise counting records using digital scanning equipment, ensuring 99.5% accuracy rates",
      "Collaborate with store management to reconcile discrepancies between physical counts and system records",
      "Adapt quickly to different retail environments and inventory management systems",
      "Work independently with minimal supervision across various locations",
      "Produce detailed inventory reports highlighting discrepancies and potential shrinkage issues"
    ],
    skills: ["Inventory Management", "Data Accuracy", "Attention to Detail", "Time Management", "Problem Solving"]
  },
  languages: [
    { name: "Sepedi", level: "Home Language", proficiency: 100 },
    { name: "Setswana", level: "Fluent", proficiency: 90 },
    { name: "English", level: "Professional", proficiency: 85 },
    { name: "IsiZulu", level: "Conversational", proficiency: 75 },
  ],
  certifications: ["Python Programming Certificate - Udemy (Self-taught)"],
  careerObjective: "Motivated and adaptable Computer Science student seeking an internship opportunity to apply and grow my skills in various technology domains. With a strong foundation in programming and problem-solving, I am eager to contribute to innovative projects across all tech fields while gaining valuable industry experience.",
  aboutMe: {
    personalJourney: "My journey into technology began with a curiosity about how digital systems work. Growing up in Pretoria, I was fascinated by computers from an early age and taught myself basic programming before entering university. This self-driven learning approach has shaped my educational path and fueled my passion for creating innovative digital solutions.",
    passions: "Beyond coding, I'm passionate about solving real-world problems through technology. I enjoy the challenge of designing intuitive user experiences and building robust backend systems that work seamlessly together. In my free time, I explore new programming languages and contribute to open-source projects to expand my technical horizons.",
    strengths: "My adaptability and quick learning abilities have allowed me to master multiple programming languages and frameworks. I thrive in collaborative environments where I can contribute my technical skills while learning from experienced professionals. My methodical approach to problem-solving helps me tackle complex challenges with confidence and precision."
  }
};
